version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    working_directory: ~/navit
    steps:
    - checkout
    - run:
        command : |
          apt-get update
          apt-get install -y gettext
          apt-get install -y libsaxonb-java
          apt-get install -y lib32stdc++6
          apt-get install -y lib32z1
          apt-get install -y python-gobject libdbus-glib-1-dev python-dev
          apt-get install -y python-pip
          pip install junit-xml dbus-python
    - run:
        command : |
          bash ci/build_linux.sh
